import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Userprovider } from "@/context/user.context";
import { Doctorprovider } from "@/context/docter.context";
import { DynamicDock } from "@/components/layout/DynamicDock";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-950">
        <Userprovider>
          <Doctorprovider>
            <DynamicDock />
            {children}
          </Doctorprovider>
        </Userprovider>
      </body>
    </html>
  );
}
